### ISSUE TITLE
Use same silt texture as VMG

### ISSUE THREAD

**Issue by Golutazem** [adrido/darkage#4]
This request is for darkage to use the same silt texture as the Valleys MapGen (VMG). The HDX texture pack has that image at
https://gitlab.com/VanessaE/hdx-512/-/blob/master/vmg_silt.jpg

**Comment by HybridDog** [comment]
I've downscaled the image: ![vmg_silt_16](https://user-images.githubusercontent.com/3192173/79561911-6c6b7a00-80aa-11ea-815b-8bdf7f83e9ce.png)
It looks like this:
![arranged_vmg_silt_16](https://user-images.githubusercontent.com/3192173/79562027-9fae0900-80aa-11ea-8fc4-374b3bff363c.png)

**Comment by Golutazem** [comment]
What I want is that when the module is used and the HDX texture pack is used, then the user should see the silt with the texture applied from the texture pack.

**Comment by adrido** [comment]
So if you have the hdx texture pack enabled, you want to see the hdx texture for silt, right?
If this is the case, you should ask https://gitlab.com/VanessaE/hdx-512 for support the darkage mod.

**Comment by HybridDog** [comment]
The support can probably be added with [Texture Overrides](https://github.com/minetest/minetest/blob/23c6d0c31f2e0a4a6032b0afb02fab1d5f9c517b/doc/texture_packs.txt#L152) or symbolic links.

**Comment by Golutazem** [comment]
Issue filed in HDX.
https://gitlab.com/VanessaE/hdx-512/-/issues/6

**Comment by Golutazem** [comment]
This now in HDX with the name darkage uses.
