### ISSUE TITLE
Tuff ores won't generated because of typos

### ISSUE THREAD

**Issue by axcore** [adrido/darkage#7]
In mapgen.lua there's a typo at line 193:

`	wherein         	= {"default:stone", "default:needs_dirt", "default:gravel", "default:stone_with_coal"},
`

...which should almost  certainly be:

`	wherein         	= {"default:stone", "default:dirt", "default:gravel", "default:stone_with_coal"},
`

The exact same typo appears at line 212, but not in line 232.

**Comment by adrido** [comment]
Thanks for the report.

Fixed in https://github.com/adrido/darkage/commit/536d635e253d8cbd1a2135191207962b4d1a87e1
